<a href="https://colab.research.google.com/github/Ravi8762/First_Semester_DataScience_GenerativeAI/blob/main/Gen_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 10

In [ ]:
# Now you can access x

In [1]:
#first program
my_sub = "Generative AI"
my_sub

'Generative AI'

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
#data type
#numeric
#integer -- absence of decimal
x = 0
type(x)


int

In [ ]:
#floating point number --- presence of decimal point
y = 1.0
type(y)

float

In [ ]:
#complex number
z  = 3+4j
type(zi)

complex

In [ ]:
#string---data in text form mostly
my_city = "Solan"
type(my_city)


str

In [ ]:
#none---nothing , empty
e = None
type(e)

NoneType

In [ ]:
#boolean---True,False
z = True
type(z)

bool

In [ ]:
c = False
type(c)

bool

In [ ]:
#arithematic operator
#addition(+)
a = 10
b = 20
c = a+b
c

30

In [ ]:
#substraction (-)
a = 10
b = 20
c = a-b
c

-10

In [ ]:
#multipicaton(*)
a = 10
b = 20
c = a*b
c

200

In [ ]:
# expontiation(**)
a = 3
b = 2
c = a**b
c

9

In [ ]:
# modulas (%)
a = 5
b = 2
c = a%b
c

1

In [ ]:
#division (/)
a = 5
b = 2
c = a/b
c

2.5

In [ ]:
#floor division(//)
a = 5
b = 2.0
c = a//b
c

2.0

In [ ]:
#compound assignment operator
a = 10
b = 20
a+=b
a
#

30

In [ ]:
a-=b
print(a)

10


In [ ]:
my_list=[1,2,3,4,5]
type(my_list)

list

In [ ]:
my_list1=["a",3.14,7,True,None]
type(my_list1)

list

In [ ]:
my_list=[78,94,32,47,89]
my_list[0]
my_list[-2]

47

In [ ]:
my_list[6:1]
[78,94,55,27,2,3,1]
my_list[6:0:-2]

[89, 32]

In [ ]:
my_list=[100,200,50,300]
min(my_list)
max(my_list)
sorted(my_list)
sorted(my_list,reverse=True)

[300, 200, 100, 50]

In [ ]:
my_list=[100,200,50,300]
print(my_list)
my_list[0]=99
print(my_list)

[100, 200, 50, 300]
[99, 200, 50, 300]


In [ ]:
my_list=[100,200,50,300]
print(my_list)
my_list.append(100) #This method used to add item end of the list
print(my_list)

[100, 200, 50, 300]
[100, 200, 50, 300, 100]


In [ ]:
my_list

[100, 200, 50, 300, 100]

In [ ]:
list1 = [47,86,90]
my_list.extend(list1)
my_list

[100, 200, 50, 300, 100, 47, 86, 90]

In [ ]:
#pop() --remove the item with the help of index
my_list.pop(0)
my_list



[]

In [ ]:
my_list = [100] # add the element 100 to the list
my_list.remove(100 ) #this method removes 100 from the list
my_list # this will print an empty list

In [ ]:
my_list = [100,200,50,300]
my_list.index(200)
my_list

[100, 200, 50, 300]

In [ ]:
my_list = [100,200,50,300]
sorted(my_list, reverse = True) #arrange your list in increasing or decreasing order

[300, 200, 100, 50]

In [ ]:
my_list = [100,200,50,300]
my_list.sort(reverse= True)
my_list

[300, 200, 100, 50]

In [ ]:
print(my_list)

[300, 200, 100, 50]


In [ ]:
my_tuple = (100,200,50,300)
type(my_tuple)

tuple

In [ ]:
x=1,2,3
type(x)

tuple

In [ ]:
y=()
type(y)

tuple

In [ ]:
z = (2)
type(z)

int

In [ ]:
a = (2,)
type(a)

tuple

In [ ]:
my_tuple = ("Ravi",3.24,8,True,None)
type(my_tuple)

tuple

In [ ]:
len(my_tuple)

5

In [ ]:
# Ensure my_tuple is defined before accessing it
my_tuple = ("Ravi",3.24,8,True,None)

# Attempting to modify a tuple will raise a TypeError, as tuples are immutable
# If you need to change the tuple, consider converting it to a list first.
# For example:
# my_list = list(my_tuple)
# my_list[0] = "Ravi"
# my_tuple = tuple(my_list)

In [ ]:
state_list = ["HP" , "UP" , "MP" , "TN" , "RJ"]
city_list = [ "SHIMLA" , "LK" , "GUR" , "CHENNAI" , "JAIPUR"]
x = zip(state_list, city_list)
x

In [ ]:
list(x)

[('HP', 'SHIMLA'),
 ('UP', 'LK'),
 ('MP', 'GUR'),
 ('TN', 'CHENNAI'),
 ('RJ', 'JAIPUR')]

In [ ]:
my_tuple = (6,7,8,5,6,4,8)
my_tuple.count(6)

2

In [ ]:
my_tuple.index(6) #find the index of first accurance

0

In [ ]:
#set -- collection of unique number of item
x = "  "
type(x)

str

In [ ]:
y = []
type(y)

list

In [ ]:
z = ()
type (z)

tuple

In [ ]:
my_set = {3,6,7,9,8}
type(my_set)

set

In [ ]:
a = {}
type(a)

dict

In [ ]:
empty_set = set()
type(empty_set)

set

In [ ]:
my_set = {4,8,9,6,3,2}
print(my_set)

{2, 3, 4, 6, 8, 9}


In [ ]:
a = set()
a.add(10)
a.add(20)
a.add(30)
a

{10, 20, 30}

In [ ]:
my_set = {34,67,89}
my_set.update([10,67,89])
print(my_set)

{10, 89, 34, 67}


In [ ]:
my_set.remove(34)
my_set

{10, 67, 89}

In [ ]:
#union--
A = {1,2,3,4,5}
B = {4,5,6,7,8}
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
#INTERSECTION
A.intersection(B)

{4, 5}

In [ ]:
A.difference(B)

{1, 2, 3}

In [ ]:
A-B

{1, 2, 3}

In [ ]:
B-A

{6, 7, 8}

In [ ]:
A.symmetric_difference(B)

{1, 2, 3, 6, 7, 8}

In [ ]:
my_dict ={"HP": "SHM", "UP": "LK", "MP": "GUR", "TN": "CHENNAI", "RJ": "JAIPUR"}
type(my_dict)

dict

In [ ]:
my_dict["HP"]

'SHM'

In [ ]:
#keys-- This method,return the keys of dictionary  { ALWAYS IMMUTABLE}
list(my_dict.keys())

['HP', 'UP', 'MP', 'TN', 'RJ']

In [ ]:
#values-- This method return values of your dictionary {IMMUTABLE OR MUTABLE BOTH}
list(my_dict.values())

['SHM', 'LK', 'GUR', 'CHENNAI', 'JAIPUR']

In [ ]:
#items-- This method return items of your dictionaty {ALWAYS MUTABLE}
my_dict.items()

dict_items([('HP', 'SHM'), ('UP', 'LK'), ('MP', 'GUR'), ('TN', 'CHENNAI'), ('RJ', 'JAIPUR')])

In [ ]:
my_dict = {"Name": "Ravi" , "Marks List" : [45,67,89]}
type(my_dict)

dict

In [ ]:
my_dict.update({"College": "Shoolini"})
print(my_dict)

{'Name': 'Ravi', 'Marks List': [45, 67, 89], 'College': 'Shoolini'}


In [ ]:
age = int(input("Enter your age: ")) # The input is converted into an integer.
if age < 21:
    print("You are too young for marriage")
elif age > 60:
    print("You are too old for marriage")
else:
    print("You are eligible for marriage .. AAJA SHADI KARLE !!")

Enter your age: 67
You are too old for marriage


In [ ]:
#for loop - this loop apply on sequence (string list,tuple and range)
my_sub = "Solan"
for i in my_sub:
  print(i)

S
o
l
a
n


In [ ]:
for i in range(0,5,1):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
#indexing
my_sub = "Machine Learning"
for i in range(len(my_sub)):
  print(my_sub[i],i)

M 0
a 1
c 2
h 3
i 4
n 5
e 6
  7
L 8
e 9
a 10
r 11
n 12
i 13
n 14
g 15


In [ ]:
my_sub = "Machine Learning"
for i in range(-1,-len(my_sub)-1,-1):
  print(my_sub[i],i)

g -1
n -2
i -3
n -4
r -5
a -6
e -7
L -8
  -9
e -10
n -11
i -12
h -13
c -14
a -15
M -16


In [ ]:
#while loop--thid loop execute upto condition is true

In [ ]:
i = 0 #initialisation
while i<5: #condition
  print(i)
  i+=1 #increment i = i+1
  print(i)

0
1
1
2
2
3
3
4
4
5


In [ ]:
#loops control statement
i = 0
while i<5:
  if i==3:
    break #break the loop
    print(i)
  else:
    print(i)
  i+=1

0
1
2


In [ ]:
i = 0
while i<5:
  i+=1
  if i==3:
    continue #continue the loop
    print(i)
  else:
    print(i)

1
2
4
5


In [ ]:
i = 0
while i<5:
  i+=1
  if i==3:
    pass #skip the current iteration
    print(i)
  else:
    print(i)

1
2
3
4
5


In [ ]:
#user defined function
def add():
  a = int(input("Enter first number: "))
  b = int(input("Enter second number: "))
  c = a+b
  return c

In [ ]:
print(add())

In [ ]:
#positional argument
def add(a,b):
  c = a+b
  return c

In [ ]:
print(add(10,20))

30


In [ ]:
#default argument
def add(a,b=10):
  c = a+b
  return c

In [ ]:
print(add(50))

60


In [ ]:
#keyword argument
def interest(p,r,t):
  i = (p*r*t)/100
  return i

In [ ]:
print(interest(p=100,r=10,t=2))

20.0


In [ ]:
#mixed arguments (positional , keyword)

In [ ]:
interest = (p,r,t)

In [ ]:
#variable length argument
#non-keyword variable length arguments
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

In [ ]:
test(10,20,30)

(10, 20, 30)
3
<class 'tuple'>


In [ ]:
def addition(*args):
  sum = 0
  for i in args:
    sum+=i
  return sum

In [ ]:
addition(3,4,5,7,12)

31

In [ ]:
#keyword variable length arguments
def test(**kwargs):
  print(kwargs)
  print(len(kwargs))
  print(type(kwargs))

In [ ]:
test(a=10,b=20,c=30)

{'a': 10, 'b': 20, 'c': 30}
3
<class 'dict'>


In [ ]:
def pass_student(**kwargs):
  pass_student_list = []
  for key,value in kwargs.items():
    if value>40:
      pass_student_list.append(key)
  return pass_student_list

In [ ]:
pass_student(A=60 , B=30 , C=40 , D=50)

['A', 'D']

In [ ]:
import numpy as np

In [ ]:
oned_array = np.array([3,4,5,6])
print(oned_array)

[3 4 5 6]


In [ ]:
twod_array = np.array([[1,2,3,4],[5,6,7,8]])
print(twod_array)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
threed_array = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(threed_array)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [ ]:
#array inspection
#shape -- find the shape of array
oned_array = np.array([3,4,5,6])
print(oned_array.shape)
oned_array.shape

(4,)


(4,)

In [ ]:
twod_array = np.array([[1,2,3,4],[5,6,7,8]])
print(twod_array.shape)

(2, 4)


(2, 4)

In [ ]:
threed_array = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(threed_array.shape)

(2, 2, 4)


In [ ]:
#ndim-- find the dimension of array
twod_array = np.array([[1,2,3,4],
                       [5,6,7,8]])
print(twod_array.ndim)
twod_array.ndim

2


2

In [ ]:
#dtype -- find the data type
twod_array.dtype

dtype('int64')

In [ ]:
#size -- total number of item in array
twod_array = np.array([[1,2,3,4],
                       [5,6,7,8]])
print(twod_array.size)
twod_array.size

8


8

In [ ]:
import numpy as np
twod_array = np.array([[1,2,3,4],
                       [5,6,7,8]])
print(twod_array)
twod_array.astype(float)

[[1 2 3 4]
 [5 6 7 8]]


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [ ]:
#zeroes array
zeroes_array = np.zeros((3,4) , dtype = int)
print(zeroes_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
ones_array = np.ones((3,4) , dtype = int)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
print(ones_array*99)

[[99 99 99 99]
 [99 99 99 99]
 [99 99 99 99]]


In [ ]:
my_array = np.full((3,4) , 100)
print(my_array)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
random_array = np.random.random((3,4))
print(random_array)

[[0.46460572 0.72551438 0.33311983 0.72207911]
 [0.45080433 0.06803131 0.76426798 0.26303649]
 [0.95537784 0.52956877 0.8746112  0.08527669]]


In [ ]:
random_intarray = np.random.randint(2,10,(3,4))
print(random_intarray)

[[3 9 3 7]
 [6 3 2 8]
 [8 9 7 7]]


In [ ]:
arrange_array = np.arange(2,20,2,dtype = float)
print(arrange_array)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [ ]:
arrange_array = np.arange(2,20,2)
print(arrange_array)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
a = np.random.randint(1,6,(2,2))
print(a)
b = np.random.randint(1,6,(2,2))
print(b)
print(a+b)

[[3 1]
 [3 5]]
[[3 4]
 [3 4]]
[[6 5]
 [6 9]]


In [ ]:
# (3,4) and (1,1)
a = np.random.randint(1,6,(3,4))
print(a)
b = np.random.randint(1,6,(1,1))
print(b)
print(a+b)

[[5 3 1 5]
 [1 2 1 5]
 [4 2 2 1]]
[[2]]
[[7 5 3 7]
 [3 4 3 7]
 [6 4 4 3]]


In [ ]:
# (1,4) and (4,1)
# (1,5) and (5,1)
a = np.random.randint(1,6,(1,4))
print(a)
b = np.random.randint(1,6,(4,1))
print(b)
print(a+b)

[[3 5 5 5]]
[[3]
 [3]
 [5]
 [4]]
[[ 6  8  8  8]
 [ 6  8  8  8]
 [ 8 10 10 10]
 [ 7  9  9  9]]


In [ ]:
#(1,4)
#(3,4)
a = np.random.randint(1,6,(1,4))
print(a)
b = np.random.randint(1,6,(3,4))
print(b)
print(a+b)

[[3 4 4 2]]
[[3 1 5 5]
 [5 2 3 2]
 [1 5 2 5]]
[[6 5 9 7]
 [8 6 7 4]
 [4 9 6 7]]
